#apiVersion: kustomize.config.k8s.io/v1beta1 <This is optional>
kind: Kustomization
bases:
  - ../base
patchesStrategicMerge:
  - update-replicas.yaml
  - set-spring-profile.yaml
 # - use-configmap.yaml
#configMapGenerator:
#  - name: dockerjib-config
#    files:
#      - application.properties