apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dockerjib-deployment
  name: dockerjib-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerjib-deployment
  template:
    metadata:
        creationTimestamp: null
        labels:
          app: dockerjib-deployment
    spec:
      containers:
        - image: "registry.hub.docker.com/pvpkiran/testingjib:first"
          name: testingjib
